// Guessing the number game.
// Created by CHINMAY JAIN.
// Dated: 09-12-2023
// chinmay jain
#include <stdio.h>
#include <stdlib.h> // used to import the random number.
#include <time.h>   // time 0 to change the number.

int main()
{
    int number_of_chances; // inputing the number of chances by the user to play this game.;
    int count = 0;
    int i = 0;
    int guess; // user guesses the number again and again;
    srand(time(0));
    int random = rand() % 100; // to getting the random number in range 0 to 100.

    printf("How many chances do you want to play?\n");
    scanf("%d", &number_of_chances);

    while (i != number_of_chances)
    {
        printf("Enter the number: ");
        scanf("%d", &guess);
        if (guess == random)
        {
            printf("Correct guess!\n");
            count += 1; // incrementing the "count" variable.
            break;
        }
        else if (guess != random)
        {
            if (guess < random)
            {
                printf("Please guess the higher number!\n");
                count += 1;
                i++; // incrementing the value of "i" for checking the condition of the while loop again and again and while loop gets exited when the condition becomes false.
                continue;
            }

            else
            {
                printf("Please guess the lower number!\n");
                count += 1;
                i++;
                continue;
            }
        }

        else
        {
            printf("Invalid input!\n");
            count += 1;
            i++;
            continue;
        }
    }

    // Printing the number generated by the system.

    if (guess != random)
    {
        printf("Better luck next time!\n");
        printf("The number was: %d\n", random);
    }

    // Printing the number of chances that the user took to guess the number.

    printf("Number of chances you took is: ");
    return printf("%d", count);
}
