// snake, water and gun


let computer_choice = undefined // Computer_choice according to the random_number : if random_number == 1 then computer will choose snake, if random_number == 2 then computer will choose water and for 3 computer will choose gun
let random_number // Initializing random number that will be generated by the computer itself
let win = 0 // Initializing the winning chance and defaultly setting it as 0\
// showing the rule of the game
alert(`There will be negative point (-1) if you loose that chance or you entered the wrong input. If chances are drawn then in that case no points will be awarded and for wining +1 point will be awarded`)
const number_of_chances = Number.parseInt(prompt('How many changes do you want to play?'))
let user_name = prompt('What is your name?')
// capitalizing the first letter of user_name 
let first_letter_user_name = user_name[0].toUpperCase()
let modifing_user_name = user_name.replace(user_name[0], first_letter_user_name)

// this variable is resposible for breaking the while loop
let encounter_variable = 0
while (encounter_variable < number_of_chances) {
  random_number = Math.floor(Math.random() * 3) + 1 // generating random number 1,2,3

  if (random_number === 1) {
    computer_choice = 'Snake'
  }
  else if (random_number === 2) {
    computer_choice = 'Water'
  }
  else {
    computer_choice = 'Gun'
  }

  let user_choice = prompt('Snake, Water and Gun: ')
  let convert_user_choice = user_choice.toLowerCase() // converting user choice to lower case so that we can minimize the error as much as possible and can matches it in the conditional statements


  // if, else if and else condition for matching the computer choice and user choice and then printing it on the webpage along with the changing the score of winning as per the choices entered by the user and choosen by the computer
  if (convert_user_choice[0] == 's') {
    if (computer_choice[0] == 'S') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`) // it will print user choice along with user name // and br tag is used to break the line as it is in the html page so \n will not work only br tag will work for new line character
      document.write(`Computer Choice: ${computer_choice}<br>`) // it will print computer choice 
      win
    }
    else if (computer_choice[0] == 'W') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win += 1
    }
    else if (computer_choice[0] == 'G') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win -= 1
    }
    else {
      document.write(`Wrong Choice is input`)
      win -= 1
    }
  }

  else if (convert_user_choice[0] == 'w') {
    if (computer_choice[0] == 'S') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win -= 1
    }
    else if (computer_choice[0] == 'W') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win
    }
    else if (computer_choice[0] == 'G') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win += 1
    }
    else {
      document.write(`Wrong Choice is input`)
      win -= 1
    }
  }


  else if (convert_user_choice[0] == 'g') {
    if (computer_choice[0] == 'S') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win += 1
    }
    else if (computer_choice[0] == 'W') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win -= 1
    }
    else if (computer_choice[0] == 'G') {
      document.write(`${modifing_user_name}: ${user_choice}<br>`)
      document.write(`Computer Choice: ${computer_choice}<br>`)
      win
    }
    else {
      document.write(`Wrong Choice is input`)
      win -= 1
    }
  }

  // Incrementing the encounter_variable so that it can breaks out the while loop
  encounter_variable += 1
}

if (win > 0) {
  alert(`Number of chances you win: ${win}`)
}
else{
  alert(`Your score is: ${win}`)
}